language: java
sudo: false
install: true

jdk:
  - oraclejdk8
  - oraclejdk11

addons:
  sonarcloud:
    organization: "annimon-github"

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.sonar/cache

branches:
  except:
    - javame
    
before_install:
 - chmod +x gradlew

after_success:
  - ./gradlew cobertura coveralls sonarqube
#  - mvn cobertura:cobertura coveralls:report
